mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth.views import login


from . import views
from transcript import views as v


urlpatterns = [
    path('register/', views.register, name='register'),
#     path('accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    path('accounts/profile/', v.list_student, name='list_student'),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('transcript/', include('transcript.urls')),
    path('webshow/', include('webshow.urls')),
    path('daozhen/', include('daozhen.urls')),
]

mysite/transcript/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path('student/list/', views.list_student, name='list_student'),
    re_path('grade/list/(?P<sn>\d{6})/$', views.list_grade, name='list_grade'),
    path('student/add/', views.add_student, name='add_student'),
    path('student/upload/', views.upload_file, name='upload_file'),
    re_path('student/update/(?P<sn>\d{6})/$', views.upt_student, name='upt_student'),
]

mysite/transcript/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    SEX_TYPE = (
        (1, '男'),
        (2, '女'),
        (3, '其它'),
    )

    sn = models.CharField(max_length=10, unique=True, verbose_name='学号')
    name = models.CharField(max_length=50, verbose_name='姓名')
    sex = models.IntegerField(choices=SEX_TYPE, verbose_name='性别')
    age = models.IntegerField(verbose_name='年龄')
    phone = models.CharField(max_length=20, default='', verbose_name='手机号')
    add_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '学生'
        verbose_name_plural = '学生信息'


class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.CharField(max_length=30, verbose_name='课程名称')
    score = models.FloatField(verbose_name='分数')
    add_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '成绩单'

mysite/transcript/views.py
# -*- encoding=utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Student
from .models import Grade
import pandas as pd
import os
from mysite.settings import BASE_DIR
# Create your views here.


def list_grade(request, sn):
    if request.method == 'GET':
        objs = Grade.objects.filter(student=Student.objects.get(sn=sn))
        return render(request, 'list_score.html', {'objs': objs})
    return Http404


@login_required
def list_student(request):
    if request.method == 'GET':
        objs = Student.objects.all()
    elif request.method == 'POST':
        condition = request.POST.get('condition', 'sn')
        content = request.POST.get('content', '')
        if condition == 'sn':
            objs = Student.objects.filter(sn=content)
        elif condition == 'name':
            objs = Student.objects.filter(name=content)
        else:
            objs = Student.objects.filter(phone=content)
    paginator = Paginator(objs, 5)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        objss = paginator.page(page)
    except PageNotAnInteger:
        objss = paginator.page(1)
    except EmptyPage:
        objss = paginator.page(paginator.num_pages)
    return render(request, 'list_student.html', {'objs': objss})


def upload_file(request):
    if request.method == 'POST':
        obj = request.FILES.get('file')
        with open(os.path.join(BASE_DIR, obj.name), 'wb') as f:
            for line in obj.chunks():
                f.write(line)
        df = pd.read_excel(os.path.join(BASE_DIR, obj.name))
        for line in df.itertuples():
            print(line)
            g = Grade()
            g.course = line[2]
            g.score = float(line[3])
            g.student = Student.objects.get(sn=line[1])
            g.save()
        return HttpResponse('上传成功')
    return Http404


def add_student(request):
    if request.method == 'GET':
        return render(request, 'add_student1.html')
    elif request.method == 'POST':
        sn = request.POST.get('sn', '')
        name = request.POST.get('name', '')
        sex = request.POST.get('sex', 0)
        age = request.POST.get('age', 0)
        phone = request.POST.get('phone', '')
        if not name or not sex or not age:
            raise Http404
        try:
            sex = int(sex)
            age = int(age)
        except ValueError:
            raise Http404
        obj = Student()
        obj.sn = sn
        obj.name = name
        obj.sex = sex
        obj.age = age
        obj.phone = phone
        obj.save()
        return HttpResponseRedirect('/transcript/student/list/')


def upt_student(request, sn):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        sex = request.POST.get('sex', 0)
        age = request.POST.get('age', 0)
        phone = request.POST.get('phone', '')
        if not name or not sex or not age:
            raise Http404
        try:
            sex = int(sex)
            age = int(age)
        except ValueError:
            raise Http404
        try:
            obj = Student.objects.get(sn=sn)
        except Student.DoesNotExist:
            raise Http404
        obj.name = name
        obj.sex = sex
        obj.age = age
        obj.phone = phone
        obj.save()
        return HttpResponseRedirect('/transcript/student/list/')
    else:
        try:
            obj = Student.objects.get(sn=sn)
        except Student.DoesNotExist:
            raise Http404
        return render(request, 'upt_student.html', {'obj': obj})

mysite/transcript/templates/add_student.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'add_student' %}">{% csrf_token %}
    <div class="form-group">
        <label for="sex">学号：</label>
        <input type="text" id="sn" name="sn" />
    </div>
    <div class="form-group">
        <label for="name">姓名：</label>
        <input type="text" id="name" name="name"/>
    </div>
    <div class="form-group">
        <label for="sex">性别：</label>
        <select id="sex" name="sex">
            <option value="1">男</option>
            <option value="2">女</option>
            <option value="3">其他</option>
        </select>
    </div>
    <div class="form-group">
        <label for="age">年龄：</label>
        <input type="text" id="age" name="age"/>
    </div>
    <div class="form-group">
        <label for="phone">手机号：</label>
        <input type="text" id="phone" name="phone"/>
    </div>
    <input type="submit" value="提交">
</form>
{% endblock %}

mysite/transcript/templates/add_student1.html
{% extends "mybase.html" %}
{% block content %}

{% endblock %}

mysite/transcript/templates/list_score.html
{% load transcripttags %}
<!DOCTYPE html>
<html lang="zh-hans">
    <head>
        <meta charset="utf-8">
        <title>mysite</title>
    </head>
    <body>
        <h1>成绩列表</h1>

        <table border="1" cellspacing="0">
            <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>科目</th>
                    <th>成绩</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objs %}
                <tr>
                    <td>{{obj.student.sn}}</td>
                    <td>{{obj.student.name}}</td>
                    <td>{{obj.course}}</td>
                    <td>{{obj.score}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

mysite/transcript/templates/list_student.html
{% load transcripttags %}
<!DOCTYPE html>
<html lang="zh-hans">
    <head>
        <meta charset="utf-8">
        <title>mysite</title>
    </head>
    <body>
        <h1>查找</h1>
        <form method="post" action="{% url 'list_student'%}">{% csrf_token %}
            <div class="form-group">
                <label for="sex">条件：</label>
                <select id="condition" name="condition">
                    <option value="sn">学号</option>
                    <option value="name">姓名</option>
                    <option value="phone">手机号</option>
                </select>
                <input type="text" id="content" name="content"/>
                <input type="submit" value="查找">
            </div>

        </form>
        <h1>上传成绩单</h1>
        <form method="post" action="{% url 'upload_file'%}"  enctype="multipart/form-data">{% csrf_token %}
            <input name="file" type="file" ><input type="submit" value="上传成绩单">

        </form>
        <h1>学生列表</h1>

        <table border="1" cellspacing="0">
            <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>年龄</th>
                    <th>手机号</th>
                    <th>成绩单</th>
                    <th>添加时间</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objs %}
                <tr>
                    <td>{{obj.sn}}</td>
                    <td>{{obj.name}}</td>
                    <td>{{obj.get_sex_display}}</td>
                    <td>{{obj.age|add:2}}</td>
                    <td>{{obj.phone|format_phone}}</td>
                    <td><a href="{% url 'list_grade' obj.sn %}">查看成绩单</a></td>
                    <td>{{obj.add_time}}</td>
                </tr>
                {% endfor %}
            </tbody>
            <div class="pagination">
                <span class="step-links">
                    {% if objs.has_previous %}
                        <a href="?page={{ objs.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">
                        第 {{ objs.number }} 页  共 {{ objs.paginator.num_pages }} 页
                    </span>

                    {% if objs.has_next %}
                        <a href="?page={{ objs.next_page_number }}">下一页</a>
                    {% endif %}
                </span>
            </div>
        </table>
    </body>
</html>

mysite/transcript/templates/upt_student.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'upt_student' obj.sn %}">{% csrf_token %}
    <div class="form-group">
        <label for="sex">学号：</label>
        <input type="text" id="sn" name="sn" value="{{obj.sn}}" readonly="True"/>
    </div>
    <div class="form-group">
        <label for="name">姓名：</label>
        <input type="text" id="name" name="name" value="{{obj.name}}"/>
    </div>
    <div class="form-group">
        <label for="sex">性别：</label>
        <select id="sex" name="sex">
            <option value="1">男</option>
            <option value="2">女</option>
            <option value="3">其他</option>
        </select>
    </div>
    <div class="form-group">
        <label for="age">年龄：</label>
        <input type="text" id="age" name="age" value="{{obj.age}}"/>
    </div>
    <div class="form-group">
        <label for="phone">手机号：</label>
        <input type="text" id="phone" name="phone" value="{{obj.phone}}"/>
    </div>
    <input type="submit" value="提交">
</form>
{% endblock %}